name: tap_code
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.4.4 <4.0.0"

dependencies:
    avatar_glow: ^3.0.1
    dynamic_color: ^1.7.0
    flutter:
        sdk: flutter
    flutter_launcher_icons: ^0.13.1
    flutter_localizations:
        sdk: flutter
    google_generative_ai: ^0.4.4
    shared_preferences: ^2.3.1
    speech_to_text: ^6.6.2
    vibration: ^1.9.0

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/icon.png"

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true

    # Enable generation of localized Strings from arb files.
    generate: true

    assets:
        # Add assets from the images directory to the application.
        - assets/images/
